This Notebook is created to be familliar with bert.
I am trying to Classify spam vs no spam emails  (Text Classification Using BERT)
I took help from this channel.
https://www.youtube.com/channel/UCh9nVJoWXmFb7sLApWGcLPQ

IMPORTANT PAGES / ARTICLES --

https://tfhub.dev/google/collections/bert/1 .

https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4 .

https://jalammar.github.io/illustrated-bert/ -- for better bert understanding

In [1]:
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

#### Import dataset 

In [2]:
import pandas as pd

df = pd.read_csv("spam.csv") ## (Dataset is taken from kaggle)
df.head(5)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [3]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [4]:
df['spam']=df['Category'].apply(lambda x: 1 if x=='spam' else 0)
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

#### Split it into training and test data set

In [5]:
## data is imbalanced

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df['Message'],df['spam'], stratify=df['spam'])

In [6]:
X_train.head(4)

5333    Neither [in sterm voice] - i'm studying. All f...
4880    Yeah just open chat and click friend lists. Th...
1257       Not yet chikku..going to room nw, i'm in bus..
600                I'm going out to buy mum's present ar.
Name: Message, dtype: object

####  importing BERT model and get embeding vectors for few sample statements

In [7]:
bert_preprocess = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3")
bert_encoder = hub.KerasLayer("https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4")

In [26]:
preprocessed_text = bert_preprocess([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"])

In [27]:
preprocessed_text.keys()

dict_keys(['input_word_ids', 'input_mask', 'input_type_ids'])

In [28]:
preprocessed_text['input_word_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[  101,  3156,  1002, 19575,  1012,  9241,  2039,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [29]:
preprocessed_text['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [30]:
preprocessed_text['input_type_ids']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [8]:
def get_sentence_embeding(sentences):
    preprocessed_text = bert_preprocess(sentences)
    return bert_encoder(preprocessed_text)['pooled_output']

In [9]:
get_sentence_embeding([
    "500$ discount. hurry up", 
    "Bhavin, are you up for a volleybal game tomorrow?"]
)

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.84351707, -0.5132728 , -0.8884573 , ..., -0.7474888 ,
        -0.7531474 ,  0.91964495],
       [-0.87208354, -0.50543964, -0.9444667 , ..., -0.858475  ,
        -0.7174534 ,  0.88082975]], dtype=float32)>

#### Get embeding vectors for few sample words. Compare them using cosine similarity 

In [10]:
e = get_sentence_embeding([
    "banana", 
    "grapes",
    "mango",
    "jeff bezos",
    "elon musk",
    "bill gates"
]
)

In [32]:
e[0].shape

TensorShape([768])

In [33]:
e[0]

<tf.Tensor: shape=(768,), dtype=float32, numpy=
array([-7.60691583e-01, -1.42193556e-01,  4.96047080e-01,  5.63457489e-01,
       -3.25448960e-01, -1.04265429e-01,  8.61495197e-01,  1.53257355e-01,
        2.36566067e-01, -9.98927772e-01,  6.37406036e-02, -2.18310002e-02,
        9.36567307e-01, -1.49260402e-01,  8.71288121e-01, -4.62801099e-01,
       -2.28479169e-02, -4.99922454e-01,  3.58854413e-01, -7.17522144e-01,
        4.18188274e-01,  6.25634432e-01,  4.98549283e-01,  2.01173544e-01,
        3.14438522e-01, -7.56920353e-02, -4.52877581e-01,  8.51691663e-01,
        8.83203864e-01,  5.80608666e-01, -5.66584945e-01,  8.72472823e-02,
       -9.43599880e-01, -1.90542608e-01,  4.81669575e-01, -9.41617906e-01,
        1.21161707e-01, -6.61138535e-01, -6.05042465e-03,  2.63378527e-02,
       -7.89631784e-01,  1.69437826e-01,  9.79319036e-01, -2.91116945e-02,
       -1.61094099e-01, -3.15732837e-01, -9.97957706e-01,  2.24020839e-01,
       -7.28060067e-01, -3.66885662e-01, -2.34596387

In [11]:
from sklearn.metrics.pairwise import cosine_similarity

# Values near to 1 means they are similar. 0 means they are very different. 
# Above you can use comparing "banana" vs "grapes" you get 0.99 similarity as they both are fruits
cosine_similarity([e[0]],[e[1]])

array([[0.99110866]], dtype=float32)

In [12]:
# Comparing banana with jeff bezos you still get 0.84 but it is not as close as 0.99 that we got with grapes

cosine_similarity([e[0]],[e[3]])

array([[0.84703803]], dtype=float32)

In [13]:
# Jeff bezos and Elon musk are more similar then Jeff bezos and banana as indicated above

cosine_similarity([e[3]],[e[4]])

array([[0.9872036]], dtype=float32)

#### Build Model

There are two types of models you can build in tensorflow.

(1) Sequential (2) Functional

So far we have built sequential model. But below we will build functional model. More information on these two is here: https://becominghuman.ai/sequential-vs-functional-model-in-keras-20684f766057

In [14]:
# Bert layers
text_input = tf.keras.layers.Input(shape=(), dtype=tf.string, name='text')
preprocessed_text = bert_preprocess(text_input)
outputs = bert_encoder(preprocessed_text)

# Neural network layers
l = tf.keras.layers.Dropout(0.1, name="dropout")(outputs['pooled_output'])
l = tf.keras.layers.Dense(1, activation='sigmoid', name="output")(l)

# Use inputs and outputs to construct a final model
model = tf.keras.Model(inputs=[text_input], outputs = [l])

In [15]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
text (InputLayer)               [(None,)]            0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        {'input_word_ids': ( 0           text[0][0]                       
__________________________________________________________________________________________________
keras_layer_1 (KerasLayer)      {'pooled_output': (N 109482241   keras_layer[0][0]                
                                                                 keras_layer[0][1]                
                                                                 keras_layer[0][2]                
______________________________________________________________________________________________

In [16]:
len(X_train)

4179

In [17]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

#### Train the model 

In [18]:
model.fit(X_train, y_train, epochs=5)

Epoch 1/5
131/131 [==============================] - 761s 6s/step - loss: 0.3227 - accuracy: 0.8662
Epoch 2/5
131/131 [==============================] - 901s 7s/step - loss: 0.2319 - accuracy: 0.8988
Epoch 3/5
131/131 [==============================] - 781s 6s/step - loss: 0.1964 - accuracy: 0.9194
Epoch 4/5
131/131 [==============================] - 756s 6s/step - loss: 0.1734 - accuracy: 0.9342
Epoch 5/5
131/131 [==============================] - 733s 6s/step - loss: 0.1579 - accuracy: 0.9447


In [19]:
model.evaluate(X_test, y_test)

44/44 [==============================] - 238s 5s/step - loss: 0.1461 - accuracy: 0.9519


[0.14611853659152985, 0.9519023895263672]

#### Inference 

In [20]:
reviews = [
    'Reply to win £100 weekly! Where will the 2006 FIFA World Cup be held? Send STOP to 87239 to end service',
    'You are awarded a SiPix Digital Camera! call 09061221061 from landline. Delivery within 28days. T Cs Box177. M221BP. 2yr warranty. 150ppm. 16 . p p£3.99',
    'it to 80488. Your 500 free text messages are valid until 31 December 2005.',
    'Hey Sam, Are you coming for a cricket game tomorrow',
    "Why don't you wait 'til at least wednesday to see if you get your ."
]
model.predict(reviews)

array([[0.5410612 ],
       [0.6333967 ],
       [0.4761097 ],
       [0.04881626],
       [0.01640821]], dtype=float32)